contentColumnType: text
fieldGroup: f013ce60-c451-4d05-8349-973abeb9dc25
handle: guidesDescription
instructions: 'Add a short description about the guide''s subject and what type of articles it may contain.'
name: Description
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: 'Add a description'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
