contentColumnType: text
fieldGroup: 49ffd94f-5461-4bda-93a5-8c8452cc77ac
handle: seoKeywords
instructions: ''
name: Keywords
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
