contentColumnType: string(240)
fieldGroup: 51354ca3-dfac-407c-b04f-646210bde672
handle: seoTitle
instructions: 'The SEO title will be shown as the title of a search result in search engines and should be descriptive about the page''s context. The optimal length is 60 characters according to [Moz](https://moz.com/learn/seo/title-tag).'
name: Title
searchable: true
settings:
  byteLimit: null
  charLimit: 60
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Search engine title'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
