fieldLayouts:
  6afa0cca-cfcd-4a19-a107-c04acf2b80c3:
    tabs:
      -
        elements:
          -
            fieldUid: f443ea6e-46fd-4c29-84a2-3589e628fbf8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 116204ff-7599-44f9-a718-580c80062bc4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 18dfc8bd-9db2-41f3-886a-7f847a04da8d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: default
name: Default
