enableVersioning: true
handle: guides
name: Guides
propagationMethod: all
siteSettings:
  6c7d1f16-a40b-4166-aa58-8c5ecf0617e2:
    enabledByDefault: true
    hasUrls: true
    template: guides
    uriFormat: '{parent.uri ?? section.handle}/{slug}'
structure:
  maxLevels: null
  uid: 856d45f6-3614-4002-aab3-63aaa40f19c9
type: structure
