enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  6c7d1f16-a40b-4166-aa58-8c5ecf0617e2:
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
